services:
  rethinkdb:
    image: rethinkdb:latest
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015

  test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
      - 4433:443
      - 4433:443/udp
    environment:
      - RDB_HOST=rethinkdb
      - RDB_PORT=28015
    volumes:
      - type: bind
        source: ./
        target: /app
        volume:
          nocopy: true
    depends_on:
      - rethinkdb